// <auto-generated />
using GestureDictionary.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestureDictionary.Migrations
{
    [DbContext(typeof(GestureContext))]
    [Migration("20240214052309_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("GestureDictionary.Models.LetterGesture", b =>
                {
                    b.Property<string>("Letter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToVideo")
                        .HasColumnType("TEXT");

                    b.HasKey("Letter");

                    b.ToTable("LetterGestures");
                });

            modelBuilder.Entity("GestureDictionary.Models.PhraseGesture", b =>
                {
                    b.Property<string>("Phrase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToVideo")
                        .HasColumnType("TEXT");

                    b.HasKey("Phrase");

                    b.ToTable("PhraseGestures");
                });

            modelBuilder.Entity("GestureDictionary.Models.WordGesture", b =>
                {
                    b.Property<string>("Word")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToVideo")
                        .HasColumnType("TEXT");

                    b.HasKey("Word");

                    b.ToTable("WordGestures");
                });
#pragma warning restore 612, 618
        }
    }
}
